# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-28 06:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_brand',
            field=models.BooleanField(default=False),
        ),
    ]
