# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-09 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Influencers'),
        ),
        migrations.AddField(
            model_name='user',
            name='ucc_handle',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='username'),
        ),
    ]
