# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-22 14:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scarface', '0004_auto_20151217_1131'),
        ('users', '0003_auto_20170222_1330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdevice',
            name='device_ptr',
        ),
        migrations.RemoveField(
            model_name='userdevice',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserDevice',
        ),
    ]
