# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-09 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20170509_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='influencer_industry',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
