# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-27 12:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userdevice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdevice',
            name='device',
        ),
        migrations.RemoveField(
            model_name='userdevice',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserDevice',
        ),
    ]
