# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-13 06:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20170613_0549'),
        ('users', '0006_auto_20170607_1216'),
    ]

    operations = [
    ]
