# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-20 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telephone_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
