# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-20 12:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_telephone_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telephone_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='address.TelephoneCode'),
        ),
    ]
