# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-07 07:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20170620_1230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='influencer_industry',
        ),
    ]
