# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-12 08:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0005_telephonecode'),
        ('users', '0011_auto_20170807_0806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='telephone_code',
        ),
        migrations.AddField(
            model_name='user',
            name='telephone_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='address.TelephoneCode'),
        ),
    ]
