# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-01 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_isFemale',
            field=models.BooleanField(default=False, help_text='Check to denote this product is for women. This is\n            an advance option and only meant if your label sells men & women products', verbose_name='Product isFemale'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_isMale',
            field=models.BooleanField(default=False, help_text='Check to denote this product is for men. This is\n            an advance option and only meant if your label sells men & women products', verbose_name='Product isMale'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_isUnisex',
            field=models.BooleanField(default=False, help_text='Check to denote this product is for men & women. This is\n            an advance option and only meant if your label sells men & women products', verbose_name='Product isUnisex'),
        ),
    ]
