# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-24 08:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_auto_20160323_1520'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('influencer_commission', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Influencer commission percentage')),
                ('brand_commission', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Brand commission percentage')),
                ('unlabel_commission', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Unlabel commission percentage')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
