# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-28 06:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_update_email_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment', '0005_brandcommission_influencercommission_unlabelcommission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('total_amount', models.DecimalField(decimal_places=5, max_digits=5, verbose_name='Total Amount Transferred')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.Order', verbose_name='Order')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Stripe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('stripe_id', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='brandcommission',
            name='amount',
            field=models.DecimalField(decimal_places=5, max_digits=5, verbose_name='Commission received'),
        ),
        migrations.AlterField(
            model_name='influencercommission',
            name='amount',
            field=models.DecimalField(decimal_places=5, max_digits=5, verbose_name='Commission received'),
        ),
        migrations.AlterField(
            model_name='unlabelcommission',
            name='amount',
            field=models.DecimalField(decimal_places=5, max_digits=5, verbose_name='Commission received'),
        ),
        migrations.AddField(
            model_name='payout',
            name='stripe_credential',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.Stripe', verbose_name='Stripe Credential'),
        ),
    ]
