# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-01 13:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_auto_20170301_1035'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stripe',
            new_name='StripeCredential',
        ),
    ]
