# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-06 07:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_update_email_length'),
        ('payment', '0010_auto_20170301_1323'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfluencerPayout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True, verbose_name='Total Amount Transferred')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.Order', verbose_name='Order')),
                ('stripe_credential', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.StripeCredential', verbose_name='Stripe Credential')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameModel(
            old_name='Payout',
            new_name='BrandPayout',
        ),
    ]
