# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-06 09:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0011_auto_20170306_0721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brandpayout',
            name='order',
        ),
        migrations.RemoveField(
            model_name='influencerpayout',
            name='order',
        ),
    ]
