# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-06 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0012_auto_20170306_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='influencerpayout',
            name='reference',
            field=models.CharField(blank=True, max_length=128, verbose_name='Reference'),
        ),
    ]
