# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-07 05:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0013_influencerpayout_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandpayout',
            name='reference',
            field=models.CharField(blank=True, max_length=128, verbose_name='Reference'),
        ),
    ]
