# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-09 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0014_brandpayout_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandcommission',
            name='added_to_total',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='influencercommission',
            name='added_to_total',
            field=models.BooleanField(default=False),
        ),
    ]
