# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-09 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0015_auto_20170309_1308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brandcommission',
            old_name='added_to_total',
            new_name='is_completed',
        ),
        migrations.RenameField(
            model_name='influencercommission',
            old_name='added_to_total',
            new_name='is_completed',
        ),
        migrations.AddField(
            model_name='unlabelcommission',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
