# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-30 10:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0016_auto_20170309_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='commissionconfiguration',
            name='last_payout_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
