# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-03 05:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0007_auto_20170328_0957'),
        ('partner', '0011_auto_20170328_0957'),
        ('payment', '0017_commissionconfiguration_last_payout_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandpayout',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='partner.Partner', verbose_name='Brand'),
        ),
        migrations.AddField(
            model_name='influencerpayout',
            name='influencer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='influencers.Influencers', verbose_name='Influencer'),
        ),
    ]
