# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-28 07:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_update_email_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailConfirmation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=250, verbose_name=b'Email')),
                ('key', models.CharField(max_length=255, verbose_name=b'Hash Key')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name=b'Created Date')),
                ('link_expired', models.BooleanField(default=False, verbose_name=b'Link Expired')),
            ],
        ),
    ]
