# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-28 07:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_update_email_length'),
    ]

    operations = [

    ]
