# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-13 10:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('partner', '0015_rentalinformation_rental_time'),
        ('customer', '0004_userproductlike_userverify'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBrandLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partner.Partner')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Brand Likes',
                'verbose_name': 'Brand Likes',
            },
        ),
        migrations.CreateModel(
            name='UserInfluencerLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Influencer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partner.Partner')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Influencer Likes',
                'verbose_name': 'Influencer Likes',
            },
        ),
    ]
