# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-06 05:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_emailconfirmation'),
    ]

    operations = [

    ]
