# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-06 06:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0030_auto_20170106_0532'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer', '0005_delete_emailconfirmation'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProductLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_like', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Product_Like',
                'verbose_name_plural': 'Product_Likes',
            },
        ),
    ]
