# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-29 13:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0003_influencers_style_preference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='influencers',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='influencers',
            name='brands',
        ),
        migrations.RemoveField(
            model_name='influencers',
            name='hometown',
        ),
        migrations.RemoveField(
            model_name='influencers',
            name='image',
        ),
        migrations.RemoveField(
            model_name='influencers',
            name='instagram_handle',
        ),
        migrations.RemoveField(
            model_name='influencers',
            name='photographer_credit',
        ),
        migrations.RemoveField(
            model_name='influencers',
            name='photographer_credit_isActive',
        ),
        migrations.RemoveField(
            model_name='influencers',
            name='question_brand_attraction',
        ),
        migrations.RemoveField(
            model_name='influencers',
            name='question_fashion_advice',
        ),
        migrations.RemoveField(
            model_name='influencers',
            name='question_favorite_season',
        ),
        migrations.RemoveField(
            model_name='influencers',
            name='question_personal_style_one',
        ),
        migrations.RemoveField(
            model_name='influencers',
            name='question_product_favorite_explanation',
        ),
        migrations.RemoveField(
            model_name='influencers',
            name='question_product_favorite_name',
        ),
        migrations.RemoveField(
            model_name='influencers',
            name='question_product_favorite_product_pairing',
        ),
        migrations.RemoveField(
            model_name='influencers',
            name='question_product_favorite_url',
        ),
        migrations.RemoveField(
            model_name='influencers',
            name='website_isActive',
        ),
        migrations.RemoveField(
            model_name='influencers',
            name='website_name',
        ),
    ]
