# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-28 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('push_notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apnsdevice',
            name='device_id',
            field=models.TextField(blank=True, db_index=True, help_text='UDID / UIDevice.identifierForVendor()', null=True, verbose_name='Device ID'),
        ),
    ]
