# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-28 10:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('push_notification', '0002_auto_20170228_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='apnsdevice',
            name='aws_subscription_arn',
            field=models.TextField(blank=True, null=True, verbose_name='GCMDevice_AWS_Topic_Subscription_ARN'),
        ),
    ]
