# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-01 09:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('push_notification', '0003_apnsdevice_aws_subscription_arn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apnsdevice',
            name='aws_subscription_arn',
            field=models.TextField(blank=True, null=True, verbose_name='APNSDevice_AWS_Topic_Subscription_ARN'),
        ),
    ]
