# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-03 15:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('push_notification', '0005_notificationdetails'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificationdetails',
            options={'verbose_name_plural': 'Notification Deatils'},
        ),
    ]
