# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-06 09:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('push_notification', '0006_auto_20170303_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationdetails',
            name='date_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notificationdetails',
            name='notification_type',
            field=models.CharField(blank=True, choices=[('pr', 'Producted Rented'), ('prl', 'Product Reservation Lost'), ('pnl', 'Product Not Live'), ('lnr', 'Live And Not Returned'), ('nba', 'New Brand Added')], max_length=4, null=True),
        ),
    ]
