# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-07 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('push_notification', '0008_auto_20170307_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationdetails',
            name='notification_type',
            field=models.CharField(blank=True, choices=[('pr', 'Producted Rented'), ('prl', 'Product Reservation Lost'), ('pnl', 'Product Not Live'), ('lnr', 'Live And Not Returned'), ('followed_brand_product_added', 'Followed Brand Added Product'), ('nba', 'New Brand Added'), ('general_notification', 'General Notification')], max_length=4, null=True),
        ),
    ]
