# -*- coding: utf-8 -*-

# Generated by Django 1.9 on 2017-01-31 04:28

from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0002_auto_20170125_0546'),
    ]

    operations = [
        migrations.CreateModel(

            name='InfluencerInvite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_sent', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(

            name='Influencers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('auto_id', models.CharField(blank=True, default='', max_length=16, null=True, unique=True, verbose_name='Influencer ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Influencers')),
                ('bio', models.TextField(blank=True, default='', verbose_name='Bio')),
                ('height', models.DecimalField(blank=True, decimal_places=3, default='', help_text='US Measurements', max_digits=10, null=True, verbose_name='Height')),
                ('chest_or_bust', models.DecimalField(blank=True, decimal_places=3, default='', help_text='US Measurements', max_digits=10, null=True, verbose_name='Chest or Bust')),
                ('hips', models.DecimalField(blank=True, decimal_places=3, default='', help_text='US Measurements', max_digits=10, null=True, verbose_name='hips')),
                ('waist', models.DecimalField(blank=True, decimal_places=3, default='', help_text='US Measurements', max_digits=10, null=True, verbose_name='waist')),
                ('location', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='address.Locations', verbose_name='Location')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
