# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-25 04:31
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('address', '0002_auto_20170125_0431'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfluencerAccountInfo',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits are allowed.", regex='^\\+?1?\\d{9,15}$')])),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'abstract': False,
            },
            bases=('users.user', models.Model),
        ),
        migrations.CreateModel(
            name='Influencers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('auto_id', models.CharField(blank=True, default='', max_length=16, null=True, unique=True, verbose_name='Influencer ID')),
                ('name', models.CharField(blank=True, default='', max_length=100, verbose_name='Name')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Influencers')),
                ('bio', models.TextField(blank=True, default='', verbose_name='Bio')),
                ('is_active', models.BooleanField(default=True, help_text='Check to activate', verbose_name='Activate/Deactivate Influencer')),
                ('height', models.DecimalField(blank=True, decimal_places=3, default='', help_text='US Measurements', max_digits=10, null=True, verbose_name='Height')),
                ('chest_or_bust', models.DecimalField(blank=True, decimal_places=3, default='', help_text='US Measurements', max_digits=10, null=True, verbose_name='Chest or Bust')),
                ('hips', models.DecimalField(blank=True, decimal_places=3, default='', help_text='US Measurements', max_digits=10, null=True, verbose_name='hips')),
                ('waist', models.DecimalField(blank=True, decimal_places=3, default='', help_text='US Measurements', max_digits=10, null=True, verbose_name='waist')),
                ('shoe_size', models.DecimalField(blank=True, decimal_places=3, default='', help_text='US Measurements', max_digits=10, null=True, verbose_name='shoe_size')),
                ('location', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='address.Locations', verbose_name='Location')),
                ('users', models.ManyToManyField(blank=True, related_name='influencers', to='influencers.InfluencerAccountInfo', verbose_name='Users')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
