# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-01 09:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('influencers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='influencers',
            name='users',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='influencers', to=settings.AUTH_USER_MODEL, verbose_name='Users'),
        ),
    ]
