# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-15 14:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0010_auto_20170213_0510'),
        ('influencers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfluencerProductedRentedDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reserved', models.DateTimeField(auto_now_add=True, verbose_name='Product Reserved Date')),
                ('influencer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='influencers.Influencers', verbose_name='Influencer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.Product', verbose_name='Product')),
            ],
            options={
                'verbose_name_plural': 'Influencer Product Reservations',
            },
        ),
    ]
