# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-02 06:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0002_auto_20170201_1340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='influencers',
            old_name='user',
            new_name='users',
        ),
    ]
