# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-31 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0002_auto_20170131_0428'),
    ]

    operations = [
        migrations.AddField(
            model_name='influencerinvite',
            name='code',
            field=models.IntegerField(default=123),
            preserve_default=False,
        ),
    ]
