# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-16 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0002_auto_20170216_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='influencerproductreserve',
            name='date_reserved',
            field=models.DateTimeField(verbose_name='Product Reserved Date'),
        ),
    ]
