# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-29 10:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0026_style_name'),
        ('influencers', '0002_influencers_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='influencers',
            name='style_Preference',
            field=models.ManyToManyField(blank=True, to='partner.Style', verbose_name='Style Preference'),
        ),
    ]
