# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-15 15:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0002_influencerproductedrenteddetails'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='influencerproductedrenteddetails',
            options={'verbose_name_plural': 'Influencer Product Rented Details'},
        ),
    ]
