# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-31 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0003_influencerinvite_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='influencerinvite',
            name='user',
        ),
        migrations.AddField(
            model_name='influencerinvite',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
