# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-27 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0003_auto_20170216_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='influencers',
            name='chest_or_bust',
            field=models.PositiveIntegerField(default=0, help_text='US Measurements', verbose_name='Chest or Bust'),
        ),
        migrations.AlterField(
            model_name='influencers',
            name='height',
            field=models.PositiveIntegerField(default=0, help_text='US Measurements', verbose_name='Height'),
        ),
        migrations.AlterField(
            model_name='influencers',
            name='hips',
            field=models.PositiveIntegerField(default=0, help_text='US Measurements', verbose_name='hips'),
        ),
        migrations.AlterField(
            model_name='influencers',
            name='waist',
            field=models.PositiveIntegerField(default=0, help_text='US Measurements', verbose_name='waist'),
        ),
    ]
