# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-15 15:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0003_auto_20170215_1501'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='influencerproductedrenteddetails',
            options={'verbose_name_plural': 'Influencer Product-Rentals'},
        ),
    ]
