# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-31 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0004_auto_20170131_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='influencerinvite',
            name='code',
            field=models.CharField(max_length=20),
        ),
    ]
