# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-15 15:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0004_auto_20170215_1503'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InfluencerProductedRentedDetails',
            new_name='InfluencerProductRentedDetails',
        ),
    ]
