# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-29 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0004_auto_20161229_1336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='influencers',
            name='slug',
        ),
        migrations.AddField(
            model_name='influencers',
            name='bio',
            field=models.TextField(blank=True, default='', verbose_name='Bio'),
        ),
    ]
