# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-03 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0005_influencerproductunreserve'),
    ]

    operations = [
        migrations.AddField(
            model_name='influencerproductreserve',
            name='date_live',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Product Live Date'),
        ),
        migrations.AddField(
            model_name='influencerproductreserve',
            name='is_live',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='influencerproductreserve',
            name='date_rented',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Product Rented Date'),
        ),
    ]
