# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-30 12:14
from __future__ import unicode_literals

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
        ('influencers', '0005_auto_20161229_1354'),
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='influencers',
            name='brands',
            field=models.ForeignKey(blank=True, default='', help_text='Please select your brand', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='applications.Brand', verbose_name='Brand name'),
        ),
        migrations.AddField(
            model_name='influencers',
            name='hometown',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='influencers.City', verbose_name='Hometown'),
        ),
        migrations.AddField(
            model_name='influencers',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=100, null=True, verbose_name='Influencer Image'),
        ),
        migrations.AddField(
            model_name='influencers',
            name='instagram_handle',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Instagram handle'),
        ),
        migrations.AddField(
            model_name='influencers',
            name='photographer_credit',
            field=models.CharField(blank=True, default='', help_text='To give credit for photographer for image', max_length=255, verbose_name='Photographer credit'),
        ),
        migrations.AddField(
            model_name='influencers',
            name='photographer_credit_isActive',
            field=models.BooleanField(default=False, help_text='Check to activate photographer credit', verbose_name='Photographer credit active'),
        ),
        migrations.AddField(
            model_name='influencers',
            name='question_brand_attraction',
            field=models.TextField(blank=True, default='', verbose_name='Brand attraction'),
        ),
        migrations.AddField(
            model_name='influencers',
            name='question_fashion_advice',
            field=models.TextField(blank=True, default='', verbose_name='Fashion advice'),
        ),
        migrations.AddField(
            model_name='influencers',
            name='question_favorite_season',
            field=models.TextField(blank=True, default='', verbose_name='Favorite season'),
        ),
        migrations.AddField(
            model_name='influencers',
            name='question_personal_style_one',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Personal style 1'),
        ),
        migrations.AddField(
            model_name='influencers',
            name='question_product_favorite_explanation',
            field=models.TextField(blank=True, default='', verbose_name='Favorite product explanation'),
        ),
        migrations.AddField(
            model_name='influencers',
            name='question_product_favorite_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Favorite product name'),
        ),
        migrations.AddField(
            model_name='influencers',
            name='question_product_favorite_product_pairing',
            field=models.TextField(blank=True, default='', verbose_name='Product pairing explanation'),
        ),
        migrations.AddField(
            model_name='influencers',
            name='question_product_favorite_url',
            field=models.URLField(blank=True, default='', max_length=255, verbose_name='Favorite product url'),
        ),
        migrations.AddField(
            model_name='influencers',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=255, verbose_name='Influencer Slug'),
        ),
        migrations.AddField(
            model_name='influencers',
            name='website_isActive',
            field=models.BooleanField(default=False, help_text='Check to activate website', verbose_name='Website active'),
        ),
        migrations.AddField(
            model_name='influencers',
            name='website_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Website name'),
        ),
    ]
