# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-31 12:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0005_auto_20170131_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='influencerinvite',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
    ]
