# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-28 09:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0006_auto_20170303_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='influencers',
            name='location',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.Locations', verbose_name='Location'),
        ),
    ]
