# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-30 12:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0007_remove_influencers_hometown'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='influencers',
            name='brands',
        ),
    ]
