# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-09 14:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0008_auto_20170406_0857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='influencers',
            name='image',
        ),
    ]
