# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-11 05:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0012_auto_20170406_0857'),
        ('influencers', '0009_remove_influencers_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='influencers',
            name='styles',
            field=models.ManyToManyField(blank=True, null=True, to='partner.Style'),
        ),
    ]
