# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-30 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0010_auto_20161230_1235'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='industry',
            options={'verbose_name': 'Industry', 'verbose_name_plural': 'Industries'},
        ),
        migrations.AddField(
            model_name='industry',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='industry',
            name='name',
            field=models.CharField(blank=True, max_length=100, unique=True, verbose_name='Industry'),
        ),
    ]
