# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-17 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0010_influencers_styles'),
    ]

    operations = [
        migrations.AddField(
            model_name='influencerproductreserve',
            name='date_picked',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Product Picked Date'),
        ),
        migrations.AddField(
            model_name='influencerproductreserve',
            name='date_return',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Product Return Date'),
        ),
    ]
