# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-30 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0011_auto_20161230_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='influencers',
            name='industry_choice',
            field=models.ManyToManyField(blank=True, to='influencers.Industry', verbose_name='Industry'),
        ),
    ]
