# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-01 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0011_auto_20170517_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='influencers',
            name='follows',
            field=models.PositiveIntegerField(default=0, verbose_name='follow count'),
        ),
    ]
