# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-30 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0012_influencers_industry_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industry',
            name='name',
            field=models.CharField(blank=True, max_length=100, unique=True, verbose_name='Industry Preferences'),
        ),
    ]
