# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-07 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0014_auto_20170807_0930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='influencers',
            name='industry',
        ),
        migrations.AddField(
            model_name='influencers',
            name='industry',
            field=models.ManyToManyField(blank=True, null=True, to='influencers.Industry', verbose_name='Industry'),
        ),
    ]
