# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-03 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0015_auto_20170102_1536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='state_or_country',
        ),
        migrations.AlterModelOptions(
            name='industry',
            options={'verbose_name': 'Industry Prefernce', 'verbose_name_plural': 'Industry Prefernces'},
        ),
        migrations.AlterField(
            model_name='industry',
            name='name',
            field=models.CharField(blank=True, max_length=100, unique=True, verbose_name='Name'),
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='StateCountry',
        ),
    ]
