# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-03 12:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import oscarapps.influencers.mixins


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0016_auto_20170103_1202'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('city', models.CharField(blank=True, default='', max_length=200, unique=True, verbose_name='City')),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
            },
            bases=(oscarapps.influencers.mixins.ValidateModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='StateCountry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(blank=True, default='', help_text='Enter your State (USA only) or Country (International only)', max_length=200, unique=True, verbose_name='Location')),
                ('location_choice', models.CharField(blank=True, choices=[('State', 'U.S.A'), ('Country', 'International')], max_length=100, verbose_name='U.S.A or International')),
            ],
            options={
                'verbose_name': 'State or Country',
                'verbose_name_plural': 'State or Country',
            },
            bases=(oscarapps.influencers.mixins.ValidateModelMixin, models.Model),
        ),
        migrations.RemoveField(
            model_name='influencers',
            name='instagram_handle',
        ),
        migrations.RemoveField(
            model_name='influencers',
            name='photographer_credit',
        ),
        migrations.RemoveField(
            model_name='influencers',
            name='photographer_credit_isActive',
        ),
        migrations.RemoveField(
            model_name='influencers',
            name='question_brand_attraction',
        ),
        migrations.RemoveField(
            model_name='influencers',
            name='question_fashion_advice',
        ),
        migrations.RemoveField(
            model_name='influencers',
            name='question_favorite_season',
        ),
        migrations.RemoveField(
            model_name='influencers',
            name='question_personal_style_one',
        ),
        migrations.RemoveField(
            model_name='influencers',
            name='question_product_favorite_explanation',
        ),
        migrations.RemoveField(
            model_name='influencers',
            name='question_product_favorite_name',
        ),
        migrations.RemoveField(
            model_name='influencers',
            name='question_product_favorite_product_pairing',
        ),
        migrations.RemoveField(
            model_name='influencers',
            name='question_product_favorite_url',
        ),
        migrations.RemoveField(
            model_name='influencers',
            name='website_isActive',
        ),
        migrations.RemoveField(
            model_name='influencers',
            name='website_name',
        ),
        migrations.AddField(
            model_name='city',
            name='state_or_country',
            field=models.ForeignKey(blank=True, help_text='Select your state or country', null=True, on_delete=django.db.models.deletion.CASCADE, to='influencers.StateCountry', verbose_name='State or Country'),
        ),
    ]
