# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-03 12:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0017_auto_20170103_1215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='state_or_country',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='StateCountry',
        ),
    ]
