# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-03 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0018_auto_20170103_1218'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='industry',
            options={'verbose_name': 'Industry Preference', 'verbose_name_plural': 'Industry Preferences'},
        ),
        migrations.AddField(
            model_name='influencers',
            name='city',
            field=models.CharField(default='city_name', max_length=30, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='influencers',
            name='country',
            field=models.CharField(default='country_name', help_text='Enter your State (USA only) or Country (International only)', max_length=200, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='industry',
            name='name',
            field=models.CharField(blank=True, max_length=100, unique=True, verbose_name='Industry Preference'),
        ),
    ]
