# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-03 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0019_auto_20170103_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='influencers',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Influencers'),
        ),
    ]
