# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-03 13:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0020_auto_20170103_1302'),
    ]

    operations = [
        migrations.RenameField(
            model_name='influencers',
            old_name='influencer_isActive',
            new_name='isActive',
        ),
    ]
