# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-03 13:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0021_auto_20170103_1311'),
    ]

    operations = [
        migrations.RenameField(
            model_name='influencers',
            old_name='country',
            new_name='state_or_country',
        ),
    ]
