# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-03 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0022_auto_20170103_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='influencers',
            name='style_Preference',
            field=models.ManyToManyField(blank=True, to='partner.Style', verbose_name='Style Preferences'),
        ),
    ]
