# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-05 14:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_locations'),
        ('influencers', '0025_influencers_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='influencers',
            name='city',
        ),
        migrations.RemoveField(
            model_name='influencers',
            name='state_or_country',
        ),
        migrations.AddField(
            model_name='influencers',
            name='location',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='address.Locations', verbose_name='Location'),
        ),
    ]
