# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-09 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0026_auto_20170105_1416'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfluencerPhysicalAttributes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.DecimalField(blank=True, decimal_places=3, help_text='US Measurements', max_digits=10, verbose_name='Height')),
                ('chest_or_bust', models.DecimalField(blank=True, decimal_places=3, help_text='US Measurements', max_digits=10, verbose_name='Chest or Bust')),
                ('hips', models.DecimalField(blank=True, decimal_places=3, help_text='US Measurements', max_digits=10, verbose_name='hips')),
                ('waist', models.DecimalField(blank=True, decimal_places=3, help_text='US Measurements', max_digits=10, verbose_name='waist')),
                ('shoe_size', models.DecimalField(blank=True, decimal_places=3, help_text='US Measurements', max_digits=10, verbose_name='shoe_size')),
            ],
        ),
        migrations.RemoveField(
            model_name='influencers',
            name='industry_choice',
        ),
        migrations.RemoveField(
            model_name='influencers',
            name='instagram_url',
        ),
        migrations.RemoveField(
            model_name='influencers',
            name='isActive',
        ),
        migrations.RemoveField(
            model_name='influencers',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='influencers',
            name='style_Preference',
        ),
        migrations.RemoveField(
            model_name='influencers',
            name='website_url',
        ),
        migrations.AlterField(
            model_name='influencers',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='influencers',
            name='physical_attributes',
            field=models.ManyToManyField(blank=True, to='influencers.InfluencerPhysicalAttributes', verbose_name='Physical Attributes'),
        ),
    ]
