# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-13 05:53
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        ('influencers', '0027_auto_20170109_1402'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfluencerAccountInfo',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits are allowed.", regex='^\\+?1?\\d{9,15}$')])),
            ],
            options={
                'verbose_name': 'user',
                'abstract': False,
                'verbose_name_plural': 'users',
            },
            bases=('auth.user', models.Model),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='influencers',
            name='location',
        ),
        migrations.RemoveField(
            model_name='influencers',
            name='physical_attributes',
        ),
        migrations.RemoveField(
            model_name='influencers',
            name='users',
        ),
        migrations.AddField(
            model_name='industry',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='industry',
            name='modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.DeleteModel(
            name='InfluencerPhysicalAttributes',
        ),
        migrations.DeleteModel(
            name='Influencers',
        ),
    ]
