# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-13 08:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0029_influencers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='influencers',
            old_name='auto_id',
            new_name='influencer_id',
        ),
    ]
