# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-13 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0032_auto_20170113_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='influencers',
            name='auto_id',
            field=models.CharField(blank=True, default='', max_length=16, null=True, unique=True, verbose_name='Influencer ID'),
        ),
    ]
