# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-16 05:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0033_auto_20170113_0949'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Industry',
        ),
        migrations.AddField(
            model_name='influencers',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Check to activate', verbose_name='Activate/Deactivate Influencer'),
        ),
    ]
