# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-17 13:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0034_auto_20170116_0520'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='influenceraccountinfo',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelManagers(
            name='influenceraccountinfo',
            managers=[
            ],
        ),
    ]
