# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-17 13:20
from __future__ import unicode_literals

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0035_auto_20170117_1311'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='influenceraccountinfo',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelManagers(
            name='influenceraccountinfo',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
