# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-25 04:31
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_auto_20170125_0431'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('partner', '0004_auto_20160107_1755'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableDateTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('date', models.DateField()),
                ('from_time', models.TimeField()),
                ('to_time', models.TimeField()),
            ],
            options={
                'verbose_name': 'Available Date And Time',
            },
        ),
        migrations.CreateModel(
            name='BrandCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(blank=True, max_length=100, unique=True, verbose_name='Category')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Brand Category',
                'verbose_name_plural': 'Brand Categories',
            },
        ),
        migrations.CreateModel(
            name='BrandStoreType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(blank=True, max_length=100, unique=True, verbose_name='Store Type')),
            ],
            options={
                'verbose_name': 'Store Type',
                'verbose_name_plural': 'Store Types',
            },
        ),
        migrations.CreateModel(
            name='BrandStyle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(blank=True, max_length=100, unique=True, verbose_name='Style')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('type', models.ManyToManyField(blank=True, to='partner.BrandStoreType', verbose_name='Brand Style')),
            ],
            options={
                'verbose_name': 'Brand Style',
                'verbose_name_plural': 'Brand Styles',
            },
        ),
        migrations.CreateModel(
            name='PartnerFollow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Brand Follows',
                'verbose_name_plural': 'Brand Follows',
            },
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(blank=True, max_length=100, unique=True, verbose_name='Style')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Style',
                'verbose_name_plural': 'Styles',
            },
        ),
        migrations.AlterModelOptions(
            name='partner',
            options={'verbose_name': 'Brands Detail'},
        ),
        migrations.AddField(
            model_name='partner',
            name='city',
            field=models.CharField(default='', max_length=20, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='partner',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits are allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AddField(
            model_name='partner',
            name='country',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='address.Country', verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='partner',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Brand Description'),
        ),
        migrations.AddField(
            model_name='partner',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='Brands', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='partner',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Check|Un check to activate|deactivate store', verbose_name='Store Active'),
        ),
        migrations.AddField(
            model_name='partner',
            name='location',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='address.Locations', verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='partner',
            name='modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='post_box',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Apartment/P.O.Box'),
        ),
        migrations.AddField(
            model_name='partner',
            name='sex_type',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('B', 'Both')], default='B', max_length=1, verbose_name='Sex Type'),
        ),
        migrations.AddField(
            model_name='partner',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=255, verbose_name='Brand Slug'),
        ),
        migrations.AddField(
            model_name='partner',
            name='state_province',
            field=models.CharField(default='', max_length=20, verbose_name='State/Province'),
        ),
        migrations.AddField(
            model_name='partner',
            name='street_address',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Street Address'),
        ),
        migrations.AddField(
            model_name='partnerfollow',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partner.Partner'),
        ),
        migrations.AddField(
            model_name='brandcategories',
            name='type',
            field=models.ManyToManyField(blank=True, to='partner.BrandStoreType', verbose_name='Brand Category'),
        ),
        migrations.AddField(
            model_name='partner',
            name='availability',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='partner.AvailableDateTime', verbose_name='Availability'),
        ),
        migrations.AddField(
            model_name='partner',
            name='store_categories',
            field=models.ManyToManyField(blank=True, to='partner.BrandCategories', verbose_name='Store Categories'),
        ),
        migrations.AddField(
            model_name='partner',
            name='store_type',
            field=models.ManyToManyField(blank=True, to='partner.BrandStoreType', verbose_name='Store Type'),
        ),
        migrations.AddField(
            model_name='partner',
            name='style_preferences',
            field=models.ManyToManyField(blank=True, to='partner.Style', verbose_name='Style Preference'),
        ),
    ]
