# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-13 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0005_auto_20170206_0453'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalinformation',
            name='end_time_period',
            field=models.CharField(blank=True, choices=[('AM', 'AM'), ('PM', 'PM')], max_length=2, null=True, verbose_name='Time Period'),
        ),
        migrations.AddField(
            model_name='rentalinformation',
            name='start_time_period',
            field=models.CharField(blank=True, choices=[('AM', 'AM'), ('PM', 'PM')], max_length=2, null=True, verbose_name='Time Period'),
        ),
    ]
