# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-27 14:06
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('address', '0002_auto_20170125_0546'),
        ('partner', '0005_auto_20170125_0546'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('category', multiselectfield.db.fields.MultiSelectField(choices=[('M', 'Menswear'), ('W', 'Womenswear')], max_length=3)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'verbose_name': 'Category',
            },
        ),
        migrations.CreateModel(
            name='ProfileInformation',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Profile Information',
            },
            bases=('users.user', models.Model),
        ),
        migrations.CreateModel(
            name='RentalAddress',
            fields=[
                ('locations_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='address.Locations')),
                ('post_box', models.CharField(blank=True, default='', max_length=20, verbose_name='Apartment/P.O.Box')),
                ('zipcode', models.CharField(blank=True, default='', max_length=10, null=True, verbose_name='Zip code')),
                ('contact_number', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits are allowed.", regex='^\\+?1?\\d{9,15}$')])),
            ],
            bases=('address.locations',),
        ),
        migrations.CreateModel(
            name='RentalTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('day', multiselectfield.db.fields.MultiSelectField(choices=[('MO', 'Monday'), ('TU', 'Tuesday'), ('WE', 'Wednesday'), ('TH', 'Thursday'), ('FR', 'Friday'), ('SA', 'Saturday'), ('SU', 'Sunday')], max_length=20)),
                ('start_time', models.TimeField(verbose_name='Start Time')),
                ('end_time', models.TimeField(verbose_name='End Time')),
            ],
            options={
                'verbose_name': 'Rental Time',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('sub_category', models.CharField(blank=True, max_length=100, unique=True, verbose_name='Sub Category')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
            ],
            options={
                'verbose_name_plural': 'Sub Categories',
                'verbose_name': 'Sub Category',
            },
        ),
        migrations.RemoveField(
            model_name='brandcategories',
            name='type',
        ),
        migrations.RemoveField(
            model_name='brandstyle',
            name='type',
        ),
        migrations.RenameField(
            model_name='style',
            old_name='name',
            new_name='style',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='availability',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='city',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='country',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='post_box',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='sex_type',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='state',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='store_categories',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='store_type',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='street_address',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='style_preferences',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='zipcode',
        ),
        migrations.AddField(
            model_name='partner',
            name='style',
            field=models.ManyToManyField(blank=True, to='partner.Style', verbose_name='Style'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='location',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='get_partner', to='address.Locations', verbose_name='Location'),
        ),
        migrations.DeleteModel(
            name='AvailableDateTime',
        ),
        migrations.DeleteModel(
            name='BrandCategories',
        ),
        migrations.DeleteModel(
            name='BrandStoreType',
        ),
        migrations.DeleteModel(
            name='BrandStyle',
        ),
        migrations.AddField(
            model_name='partner',
            name='category',
            field=models.ManyToManyField(blank=True, to='partner.Category', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='partner',
            name='profile_info',
            field=models.ManyToManyField(blank=True, to='partner.ProfileInformation', verbose_name='Profile Information'),
        ),
        migrations.AddField(
            model_name='partner',
            name='rental_address',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='partner.RentalAddress', verbose_name='Rental Address'),
        ),
        migrations.AddField(
            model_name='partner',
            name='rental_time',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='partner.RentalTime', verbose_name='Rental Time'),
        ),
        migrations.AddField(
            model_name='partner',
            name='sub_category',
            field=models.ManyToManyField(blank=True, to='partner.SubCategory', verbose_name='Category'),
        ),
    ]
