# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-27 05:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0005_auto_20161227_0557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partneraddress',
            name='description',
        ),
    ]
