# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-02 08:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0006_auto_20170201_0939'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partner',
            options={'verbose_name': 'Partner'},
        ),
    ]
