# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-01 12:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0006_auto_20170201_0939'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='style',
            old_name='style',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='subcategory',
            old_name='sub_category',
            new_name='name',
        ),
    ]
