# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-27 05:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0006_remove_partneraddress_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='partneraddress',
            name='description',
            field=models.TextField(blank=True, default=b'', verbose_name='Description'),
        ),
    ]
