# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-10 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0006_auto_20170216_1330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='style',
            name='description',
        ),
        migrations.AlterField(
            model_name='style',
            name='name',
            field=models.CharField(choices=[('M', 'Menswear'), ('F', 'Womenswear')], default='M', max_length=1, verbose_name='Name'),
        ),
    ]
