# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-01 12:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0007_auto_20170201_1207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileinformation',
            name='created',
        ),
        migrations.RemoveField(
            model_name='profileinformation',
            name='modified',
        ),
    ]
