# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-01 13:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('authtoken', '0002_auto_20160226_1747'),
        ('socialaccount', '0003_extra_data_default_dict'),
        ('address', '0002_auto_20170125_0546'),
        ('admin', '0002_logentry_remove_auto_add'),
        ('offer', '0002_auto_20151210_1053'),
        ('tastypie', '0001_initial'),
        ('voucher', '0001_initial'),
        ('influencers', '0002_auto_20170201_1340'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0002_email_max_length'),
        ('basket', '0007_slugfield_noop'),
        ('order', '0005_update_email_length'),
        ('wishlists', '0002_auto_20160111_1108'),
        ('payment', '0003_auto_20160323_1520'),
        ('reviews', '0002_update_email_length'),
        ('analytics', '0002_auto_20140827_1705'),
        ('customer', '0005_auto_20170130_1317'),
        ('partner', '0007_auto_20170201_1207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileinformation',
            name='user_ptr',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='profile_info',
        ),
        migrations.AddField(
            model_name='partner',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partner_users', to=settings.AUTH_USER_MODEL, verbose_name='Profile Information'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Menswear', 'Menswear'), ('Womenswear', 'Womenswear')], max_length=19),
        ),
        migrations.AlterField(
            model_name='partner',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=255, null=True, verbose_name='Brand Slug'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='sub_category',
            field=models.ManyToManyField(blank=True, to='partner.SubCategory', verbose_name='Sub category'),
        ),
        migrations.AlterField(
            model_name='partnerfollow',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Customer'),
        ),
        migrations.AlterField(
            model_name='partnerfollow',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='partner.Partner', verbose_name='Partner'),
        ),
        migrations.AlterField(
            model_name='rentaladdress',
            name='post_box',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Apartment/P.O.Box'),
        ),
        migrations.AlterField(
            model_name='rentaltime',
            name='day',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=56),
        ),
        migrations.AlterField(
            model_name='rentaltime',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='End Time'),
        ),
        migrations.AlterField(
            model_name='rentaltime',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Start Time'),
        ),
        migrations.AlterField(
            model_name='style',
            name='description',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='style',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='description',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Name'),
        ),
        migrations.DeleteModel(
            name='ProfileInformation',
        ),
    ]
