# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-27 06:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0007_partneraddress_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partneraddress',
            name='sex_type',
            field=models.CharField(choices=[(b'M', b'Male'), (b'F', b'Female'), (b'B', b'Both')], default=b'B', max_length=1, verbose_name='Sex Type'),
        ),
    ]
