# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-03 14:22
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('authtoken', '0002_auto_20160226_1747'),
        ('payment', '0003_auto_20160323_1520'),
        ('basket', '0007_slugfield_noop'),
        ('socialaccount', '0003_extra_data_default_dict'),
        ('order', '0005_update_email_length'),
        ('analytics', '0002_auto_20140827_1705'),
        ('wishlists', '0002_auto_20160111_1108'),
        ('tastypie', '0001_initial'),
        ('voucher', '0001_initial'),
        ('admin', '0002_logentry_remove_auto_add'),
        ('address', '0002_auto_20170125_0546'),
        ('account', '0002_email_max_length'),
        ('customer', '0005_auto_20170130_1317'),
        ('reviews', '0002_update_email_length'),
        ('offer', '0002_auto_20151210_1053'),
        ('influencers', '0003_auto_20170202_0638'),
        ('partner', '0007_auto_20170201_1207'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalInformation',
            fields=[
                ('locations_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='address.Locations')),
                ('post_box', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Apartment/P.O.Box')),
                ('zipcode', models.CharField(blank=True, default='', max_length=10, null=True, verbose_name='Zip code')),
                ('contact_number', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits are allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('day', multiselectfield.db.fields.MultiSelectField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=56)),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Start Time')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='End Time')),
            ],
            options={
                'verbose_name': 'Rental Information',
            },
            bases=('address.locations',),
        ),
        migrations.RemoveField(
            model_name='profileinformation',
            name='user_ptr',
        ),
        migrations.RemoveField(
            model_name='rentaladdress',
            name='locations_ptr',
        ),
        migrations.AlterModelOptions(
            name='partner',
            options={'ordering': ('name', 'code'), 'permissions': (('dashboard_access', 'Can access dashboard'),), 'verbose_name': 'Fulfillment partner', 'verbose_name_plural': 'Fulfillment partners'},
        ),
        migrations.RemoveField(
            model_name='partner',
            name='profile_info',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='rental_address',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='rental_time',
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Menswear', 'Menswear'), ('Womenswear', 'Womenswear')], max_length=19),
        ),
        migrations.AlterField(
            model_name='partner',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=255, null=True, verbose_name='Brand Slug'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='sub_category',
            field=models.ManyToManyField(blank=True, to='partner.SubCategory', verbose_name='Sub category'),
        ),
        migrations.AlterField(
            model_name='partnerfollow',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Customer'),
        ),
        migrations.AlterField(
            model_name='partnerfollow',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='partner.Partner', verbose_name='Partner'),
        ),
        migrations.AlterField(
            model_name='style',
            name='description',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='style',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='description',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Name'),
        ),
        migrations.DeleteModel(
            name='ProfileInformation',
        ),
        migrations.DeleteModel(
            name='RentalAddress',
        ),
        migrations.DeleteModel(
            name='RentalTime',
        ),
        migrations.AddField(
            model_name='partner',
            name='rental_info',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='partner.RentalInformation', verbose_name='Rental Informaton'),
        ),
    ]
