# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-10 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0007_auto_20170310_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='style',
            name='name',
            field=models.CharField(choices=[('Menswear', 'Menswear'), ('Womenswear', 'Womenswear')], default='Menswear', max_length=1, verbose_name='Name'),
        ),
    ]
