# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-01 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0008_auto_20170201_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileinformation',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='profileinformation',
            name='modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
