# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-01 14:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0008_auto_20170201_1344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='user',
        ),
    ]
