# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-03 10:36
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_auto_20170125_0546'),
        ('influencers', '0003_auto_20170202_0638'),
        ('partner', '0009_remove_partner_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalInformation',
            fields=[
                ('locations_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='address.Locations')),
                ('post_box', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Apartment/P.O.Box')),
                ('zipcode', models.CharField(blank=True, default='', max_length=10, null=True, verbose_name='Zip code')),
                ('contact_number', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits are allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('day', multiselectfield.db.fields.MultiSelectField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=56)),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Start Time')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='End Time')),
            ],
            options={
                'verbose_name': 'Rental Time',
            },
            bases=('address.locations',),
        ),
        migrations.RemoveField(
            model_name='rentaladdress',
            name='locations_ptr',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='rental_address',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='rental_time',
        ),
        migrations.DeleteModel(
            name='RentalAddress',
        ),
        migrations.DeleteModel(
            name='RentalTime',
        ),
        migrations.AddField(
            model_name='partner',
            name='rental_info',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='partner.RentalInformation', verbose_name='Rental Informaton'),
        ),
    ]
