# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-28 09:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0010_auto_20170310_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='location',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='get_partner', to='address.Locations', verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='rental_info',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='partner.RentalInformation', verbose_name='Rental Informaton'),
        ),
    ]
