# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-27 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0027_product_likes'),
        ('partner', '0010_auto_20161227_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='category_style',
            field=models.ManyToManyField(blank=True, to='catalogue.ProductCategory', verbose_name='Category'),
        ),
    ]
