# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-27 10:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0011_partner_category_style'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partner',
            old_name='category_style',
            new_name='category',
        ),
    ]
