# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-16 06:17
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0012_auto_20170406_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalinformation',
            name='day_1',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=56, null=True),
        ),
        migrations.AddField(
            model_name='rentalinformation',
            name='end_time_1',
            field=models.TimeField(blank=True, null=True, verbose_name='End Time'),
        ),
        migrations.AddField(
            model_name='rentalinformation',
            name='end_time_period_1',
            field=models.CharField(blank=True, choices=[('AM', 'AM'), ('PM', 'PM')], max_length=2, null=True, verbose_name='Time Period'),
        ),
        migrations.AddField(
            model_name='rentalinformation',
            name='start_time_1',
            field=models.TimeField(blank=True, null=True, verbose_name='Start Time'),
        ),
        migrations.AddField(
            model_name='rentalinformation',
            name='start_time_period_1',
            field=models.CharField(blank=True, choices=[('AM', 'AM'), ('PM', 'PM')], max_length=2, null=True, verbose_name='Time Period'),
        ),
    ]
