# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-27 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0013_auto_20161227_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='test',
            field=models.URLField(blank=True, max_length=128, verbose_name='Test'),
        ),
    ]
