# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-16 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0013_auto_20170516_0617'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=120)),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Start Time')),
                ('start_time_period', models.CharField(blank=True, choices=[('AM', 'AM'), ('PM', 'PM')], max_length=2, null=True, verbose_name='Time Period')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='End Time')),
                ('end_time_period', models.CharField(blank=True, choices=[('AM', 'AM'), ('PM', 'PM')], max_length=2, null=True, verbose_name='Time Period')),
            ],
            options={
                'verbose_name': 'Rental Time',
            },
        ),
        migrations.RemoveField(
            model_name='rentalinformation',
            name='day_1',
        ),
        migrations.RemoveField(
            model_name='rentalinformation',
            name='end_time_1',
        ),
        migrations.RemoveField(
            model_name='rentalinformation',
            name='end_time_period_1',
        ),
        migrations.RemoveField(
            model_name='rentalinformation',
            name='start_time_1',
        ),
        migrations.RemoveField(
            model_name='rentalinformation',
            name='start_time_period_1',
        ),
    ]
