# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-27 13:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0014_partner_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='test',
        ),
    ]
