# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-16 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0014_auto_20170516_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalinformation',
            name='rental_time',
            field=models.ManyToManyField(blank=True, null=True, to='partner.RentalTime'),
        ),
    ]
