# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-28 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0015_remove_partner_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='style',
            name='name',
            field=models.CharField(blank=True, max_length=128, verbose_name='Name'),
        ),
    ]
