# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-28 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0016_auto_20161228_1323'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='style',
            options={},
        ),
        migrations.AlterField(
            model_name='partner',
            name='style_Preference',
            field=models.ManyToManyField(blank=True, to='partner.Style', verbose_name='Style Preference'),
        ),
    ]
