# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-28 14:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0017_auto_20161228_1421'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='style',
            options={'verbose_name': 'Style', 'verbose_name_plural': 'Styles'},
        ),
    ]
