# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-29 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0026_style_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='style',
            name='name',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
