# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-29 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0027_auto_20161229_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='style',
            name='name',
            field=models.CharField(blank=True, max_length=128, verbose_name='Name'),
        ),
    ]
