# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-30 11:04
from __future__ import unicode_literals

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0028_auto_20161229_1310'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='style',
            options={'verbose_name': 'Style', 'verbose_name_plural': 'Styles'},
        ),
        migrations.RenameField(
            model_name='partner',
            old_name='description',
            new_name='brand_description',
        ),
        migrations.RenameField(
            model_name='partner',
            old_name='is_active',
            new_name='brand_isActive',
        ),
        migrations.RenameField(
            model_name='partner',
            old_name='style_Preference',
            new_name='brand_style',
        ),
        migrations.RenameField(
            model_name='partner',
            old_name='website_url',
            new_name='brand_website_url',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='image',
        ),
        migrations.AddField(
            model_name='partner',
            name='brand_feature_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=100, null=True, verbose_name=b'Featured Brand Image'),
        ),
        migrations.AlterField(
            model_name='style',
            name='name',
            field=models.CharField(blank=True, max_length=100, unique=True, verbose_name='Style'),
        ),
    ]
