# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-06 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0040_auto_20170106_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='isActive',
            field=models.BooleanField(default=True, help_text='Check|Un check to activate|deactivate store', verbose_name='Store Active'),
        ),
    ]
