# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-06 14:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0041_auto_20170106_1448'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brandcategories',
            options={'verbose_name': 'Brand Category', 'verbose_name_plural': 'Brand Categories'},
        ),
    ]
