# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-06 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0042_auto_20170106_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandcategories',
            name='categories',
            field=models.CharField(blank=True, max_length=100, unique=True, verbose_name='Category'),
        ),
    ]
