# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-09 09:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0043_auto_20170106_1457'),
        ('partner', '0038_auto_20170106_0532'),
    ]

    operations = [
    ]
