# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-10 05:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0045_brandstyle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentalinformation',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='rentalinformation',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='rentalinformation',
            name='line1',
        ),
        migrations.RemoveField(
            model_name='rentalinformation',
            name='line2',
        ),
        migrations.RemoveField(
            model_name='rentalinformation',
            name='line3',
        ),
        migrations.RemoveField(
            model_name='rentalinformation',
            name='line4',
        ),
        migrations.RemoveField(
            model_name='rentalinformation',
            name='postcode',
        ),
        migrations.RemoveField(
            model_name='rentalinformation',
            name='search_text',
        ),
        migrations.RemoveField(
            model_name='rentalinformation',
            name='state',
        ),
        migrations.RemoveField(
            model_name='rentalinformation',
            name='title',
        ),
        migrations.AddField(
            model_name='rentalinformation',
            name='city',
            field=models.CharField(default='', max_length=20, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='rentalinformation',
            name='state_province',
            field=models.CharField(default='', max_length=20, verbose_name='State/Province'),
        ),
        migrations.AddField(
            model_name='rentalinformation',
            name='street_address',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Street Address'),
        ),
        migrations.AlterField(
            model_name='rentalinformation',
            name='country',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='address.Country', verbose_name='Country'),
        ),
    ]
