# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-10 06:52
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0003_auto_20170106_0552'),
        ('partner', '0046_auto_20170110_0537'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentalinformation',
            name='availability',
        ),
        migrations.RemoveField(
            model_name='rentalinformation',
            name='country',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='rental_info',
        ),
        migrations.AddField(
            model_name='partner',
            name='availability',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='partner.AvailableDateTime', verbose_name='Availability'),
        ),
        migrations.AddField(
            model_name='partner',
            name='city',
            field=models.CharField(default='', max_length=20, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='partner',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits are allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AddField(
            model_name='partner',
            name='country',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='address.Country', verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='partner',
            name='post_box',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Apartment/P.O.Box'),
        ),
        migrations.AddField(
            model_name='partner',
            name='state_province',
            field=models.CharField(default='', max_length=20, verbose_name='State/Province'),
        ),
        migrations.AddField(
            model_name='partner',
            name='street_address',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Street Address'),
        ),
        migrations.DeleteModel(
            name='RentalInformation',
        ),
    ]
