# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-11 10:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0047_auto_20170110_0652'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brandcategories',
            old_name='categories',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='brandstoretype',
            old_name='store_type',
            new_name='name',
        ),
    ]
