# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-11 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0048_auto_20170111_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandcategories',
            name='type',
            field=models.ManyToManyField(blank=True, to='partner.BrandStoreType', verbose_name='Brand Category'),
        ),
        migrations.AlterField(
            model_name='brandstyle',
            name='type',
            field=models.ManyToManyField(blank=True, to='partner.BrandStoreType', verbose_name='Brand Style'),
        ),
    ]
