# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-16 05:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0050_auto_20170113_0553'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partner',
            old_name='isActive',
            new_name='is_active',
        ),
    ]
