# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-17 06:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0010_auto_20170117_0613'),
        ('partner', '0051_auto_20170116_0520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='state_province',
        ),
        migrations.AddField(
            model_name='partner',
            name='state',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='address.States', verbose_name='State'),
        ),
    ]
