# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-17 12:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('partner', '0051_auto_20170116_0520'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerFollow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Brand Follows',
                'verbose_name_plural': 'Brand Follows',
            },
        ),
        migrations.AlterModelOptions(
            name='partner',
            options={'verbose_name': 'Brands Detail'},
        ),
        migrations.AddField(
            model_name='partnerfollow',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partner.Partner'),
        ),
    ]
