# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-17 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0052_auto_20170117_0613'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='zipcode',
            field=models.CharField(blank=True, default='', max_length=10, null=True, verbose_name='Zip code'),
        ),
    ]
