# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-05 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, default=b'', max_length=200, unique=True, verbose_name='City')),
                ('state_or_country', models.CharField(blank=True, default=b'', help_text='Enter your State (USA only) or Country (International only)', max_length=200, unique=True, verbose_name='Location')),
                ('location_choice', models.CharField(blank=True, choices=[(b'State', b'U.S.A'), (b'Country', b'International')], max_length=100, verbose_name='U.S.A or International')),
                ('latitude', models.DecimalField(blank=True, decimal_places=5, max_digits=8, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=5, max_digits=8, null=True)),
            ],
        ),
    ]
