# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-28 09:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_auto_20170125_0546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locations',
            name='country',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.Country', verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='locations',
            name='state',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.States', verbose_name='State'),
        ),
    ]
