# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-06 05:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_locations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locations',
            name='city',
            field=models.CharField(blank=True, default='', max_length=200, unique=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='locations',
            name='location_choice',
            field=models.CharField(blank=True, choices=[('State', 'U.S.A'), ('Country', 'International')], max_length=100, verbose_name='U.S.A or International'),
        ),
        migrations.AlterField(
            model_name='locations',
            name='state_or_country',
            field=models.CharField(blank=True, default='', help_text='Enter your State (USA only) or Country (International only)', max_length=200, unique=True, verbose_name='Location'),
        ),
    ]
