# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-04 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0003_auto_20170328_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='locations',
            name='is_brand_location',
            field=models.BooleanField(default=False, verbose_name='Brand Location'),
        ),
        migrations.AddField(
            model_name='locations',
            name='is_influencer_location',
            field=models.BooleanField(default=False, verbose_name='Influencer Location'),
        ),
        migrations.AlterField(
            model_name='locations',
            name='country',
            field=models.CharField(default='', max_length=200, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='locations',
            name='state',
            field=models.CharField(default='', max_length=200, verbose_name='State'),
        ),
    ]
