# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-20 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0004_auto_20170404_0747'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelephoneCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10)),
            ],
        ),
    ]
