# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-11 12:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0004_states'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='states',
            options={'verbose_name': 'State in US', 'verbose_name_plural': 'States in US'},
        ),
        migrations.RemoveField(
            model_name='locations',
            name='location_choice',
        ),
        migrations.RemoveField(
            model_name='locations',
            name='state_or_country',
        ),
        migrations.AddField(
            model_name='locations',
            name='country',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='address.Country', verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='locations',
            name='state',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='address.States', verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='locations',
            name='city',
            field=models.CharField(default='', max_length=200, unique=True, verbose_name='City'),
        ),
    ]
