# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-11 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0005_auto_20170111_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locations',
            name='city',
            field=models.CharField(default='', max_length=200, verbose_name='City'),
        ),
    ]
