# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-11 12:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0006_auto_20170111_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locations',
            name='state',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='address.States', verbose_name='State'),
        ),
    ]
