# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-11 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0007_auto_20170111_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='states',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
