# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-17 06:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0009_auto_20170112_0629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='states',
            name='state',
        ),
        migrations.AddField(
            model_name='states',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='locations',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='locations',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude'),
        ),
    ]
