# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-30 13:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0004_auto_20160107_1755'),
        ('catalogue', '0009_slugfield_noop'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AddField(
            model_name='category',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='asin_id',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='ASIN'),
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='partner.Partner', verbose_name='Brand'),
        ),
        migrations.AddField(
            model_name='product',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='gcid_id',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='GCID'),
        ),
        migrations.AddField(
            model_name='product',
            name='gtnn_id',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='GTNN'),
        ),
        migrations.AddField(
            model_name='product',
            name='item_sex_type',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unisex')], default='U', max_length=1),
        ),
        migrations.AddField(
            model_name='product',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='material_info',
            field=models.TextField(blank=True, default='', verbose_name='Material Information'),
        ),
        migrations.AddField(
            model_name='product',
            name='modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='on_sale',
            field=models.BooleanField(default=True, verbose_name='Product on sale'),
        ),
        migrations.AddField(
            model_name='product',
            name='rental_status',
            field=models.CharField(choices=[('NON', 'None'), ('REN', 'Rented'), ('RET', 'Returned')], default='NON', max_length=3, verbose_name='Rental Status'),
        ),
        migrations.AddField(
            model_name='product',
            name='requires_shipping',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='Y', max_length=1, verbose_name='Requires shipping.?'),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('U', 'Unreserved'), ('R', 'Reserved'), ('D', 'Draft'), ('L', 'Live')], default='U', max_length=1, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='product',
            name='ups_id',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='UPS'),
        ),
        migrations.AddField(
            model_name='product',
            name='wieght',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
