# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-27 07:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0009_slugfield_noop'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='care_info_description',
            field=models.TextField(blank=True, default=b'', verbose_name='Care Information'),
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, default=b'', max_length=10, unique=True, verbose_name='Color'),
        ),
        migrations.AddField(
            model_name='product',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='item_sex_type',
            field=models.CharField(choices=[(b'M', b'Male'), (b'F', b'Female'), (b'U', b'Unisex')], default=b'U', max_length=1),
        ),
        migrations.AddField(
            model_name='product',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='size_and_fit_description',
            field=models.TextField(blank=True, default=b'', verbose_name='Size And Fit Information'),
        ),
    ]
