# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-13 05:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0005_auto_20170213_0502'),
        ('catalogue', '0009_slugfield_noop'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfluencerProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original', models.ImageField(max_length=255, upload_to='images/products/%Y/%m/', verbose_name='Original')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Caption')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='An image with a display order of zero will be the primary image for a product', verbose_name='Display order')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
            ],
            options={
                'verbose_name': 'Influencer product image',
                'ordering': ['display_order'],
                'verbose_name_plural': 'influencer product images',
            },
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='partner.Partner', verbose_name='Brand'),
        ),
        migrations.AddField(
            model_name='product',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='influencer_description',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Influencer Product Description'),
        ),
        migrations.AddField(
            model_name='product',
            name='item_sex_type',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unisex')], default='U', max_length=1),
        ),
        migrations.AddField(
            model_name='product',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='material_info',
            field=models.TextField(blank=True, default='', verbose_name='Material & Care Information'),
        ),
        migrations.AddField(
            model_name='product',
            name='modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='on_sale',
            field=models.BooleanField(default=True, verbose_name='Product on sale'),
        ),
        migrations.AddField(
            model_name='product',
            name='rental_status',
            field=models.CharField(choices=[('NON', 'None'), ('REN', 'Rented'), ('RET', 'Returned')], default='NON', max_length=3, verbose_name='Rental Status'),
        ),
        migrations.AddField(
            model_name='product',
            name='requires_shipping',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='Y', max_length=1, verbose_name='Requires shipping.?'),
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('U', 'Unreserved'), ('R', 'Reserved'), ('D', 'Draft'), ('L', 'Live')], default='U', max_length=1, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Product weight information'),
        ),
        migrations.AddField(
            model_name='influencerproductimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='influencer_product_images', to='catalogue.Product', verbose_name='Product'),
        ),
        migrations.AlterUniqueTogether(
            name='influencerproductimage',
            unique_together=set([('product', 'display_order')]),
        ),
    ]
