# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-16 12:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0010_auto_20170216_0557'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='influencerproductimage',
            options={'ordering': ['display_order'], 'verbose_name': 'Influencer product image', 'verbose_name_plural': 'Influencer product images'},
        ),
    ]
