# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-01 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0010_auto_20170130_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='influencer_description',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Influencer Product Description'),
        ),
        migrations.AddField(
            model_name='product',
            name='information',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Material care Information'),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Product weight information'),
        ),
    ]
