# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-27 07:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0010_auto_20161227_0723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='product',
            name='modified_date',
        ),
    ]
