# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-09 08:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0011_auto_20170209_0644'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfluencerProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original', models.ImageField(max_length=255, upload_to='images/products/%Y/%m/', verbose_name='Original')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Caption')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='An image with a display order of zero will be the primary image for a product', verbose_name='Display order')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='influencer_product_images', to='catalogue.Product', verbose_name='Product')),
            ],
            options={
                'verbose_name_plural': 'influencer product images',
                'verbose_name': 'Influencer product image',
                'ordering': ['display_order'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='influencerproductimage',
            unique_together=set([('product', 'display_order')]),
        ),
    ]
