# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-21 09:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0012_auto_20170217_0533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='size',
            name='size_class',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size_class',
        ),
        migrations.DeleteModel(
            name='Size',
        ),
        migrations.DeleteModel(
            name='SizeClass',
        ),
    ]
