# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-14 06:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0013_remove_product_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('size_sex_type', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unisex')], max_length=1, null=True, verbose_name='Size sex type')),
                ('size', models.CharField(blank=True, max_length=100, null=True, verbose_name='Size')),
            ],
            options={
                'verbose_name': 'Size',
                'verbose_name_plural': 'Sizes',
            },
        ),
        migrations.CreateModel(
            name='SizeClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Size Class')),
            ],
            options={
                'verbose_name': 'Size Class',
                'verbose_name_plural': 'Size Classes',
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='influencer_description',
        ),
        migrations.AddField(
            model_name='product',
            name='influencer_product_note',
            field=models.TextField(blank=True, null=True, verbose_name='Influencer product Note'),
        ),
        migrations.AlterField(
            model_name='influencerproductimage',
            name='original',
            field=models.ImageField(max_length=255, upload_to='Influencer Product Images', verbose_name='Original'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='partner.Partner', verbose_name='Brand'),
        ),
        migrations.AlterField(
            model_name='product',
            name='material_info',
            field=models.TextField(blank=True, default='', verbose_name='Material & care information'),
        ),
        migrations.AlterField(
            model_name='product',
            name='rental_status',
            field=models.CharField(choices=[('NON', 'None'), ('REN', 'Rented'), ('RET', 'Returned')], default='NON', max_length=3, verbose_name='Rental status'),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=8, null=True, verbose_name='Weight information'),
        ),
        migrations.AddField(
            model_name='size',
            name='size_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogue.SizeClass', verbose_name='Size class'),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.ManyToManyField(blank=True, null=True, to='catalogue.Size', verbose_name='Size'),
        ),
        migrations.AddField(
            model_name='product',
            name='size_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogue.SizeClass', verbose_name='Size class'),
        ),
    ]
