# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-27 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0016_auto_20161227_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='likes',
            field=models.IntegerField(default=1),
        ),
    ]
