# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-27 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0017_auto_20161227_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='likes',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Likes'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.IntegerField(null=True, verbose_name='Size'),
        ),
    ]
