# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-27 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0018_auto_20161227_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='likes',
            field=models.IntegerField(default=0, verbose_name='Likes'),
        ),
    ]
