# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-27 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0020_remove_product_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.IntegerField(null=True),
        ),
    ]
