# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-27 09:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0022_auto_20161227_0957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='likes',
        ),
    ]
