# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-27 09:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0023_remove_product_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='created',
        ),
        migrations.RemoveField(
            model_name='product',
            name='modified',
        ),
    ]
