# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-09 09:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0030_auto_20170106_0532'),
        ('catalogue', '0032_auto_20170106_0704'),
    ]

    operations = [
    ]
