# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-09 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0034_auto_20170109_0950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='care_info_description',
        ),
        migrations.AddField(
            model_name='product',
            name='material_info',
            field=models.TextField(blank=True, default='', verbose_name='Material Information'),
        ),
    ]
