# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-09 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0035_auto_20170109_1253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_currency',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_isActive',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_url',
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('U', 'Unselected'), ('S', 'Selected'), ('D', 'Draft'), ('L', 'Live')], default='U', max_length=1),
        ),
        migrations.DeleteModel(
            name='Colors',
        ),
    ]
