# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-09 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0036_auto_20170109_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rental_status',
            field=models.CharField(choices=[('REN', 'Rented'), ('RET', 'Returned')], default='REN', max_length=3),
        ),
    ]
