# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-09 13:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0037_product_rental_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='influencers',
        ),
    ]
