# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-12 12:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0047_auto_20170110_0652'),
        ('catalogue', '0038_remove_product_influencers'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='partner.Partner', verbose_name='Brand Information'),
        ),
    ]
