# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-10 06:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0035_auto_20170109_1137'),
        ('catalogue', '0038_remove_product_influencers'),
    ]

    operations = [
    ]
