# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-13 05:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0038_remove_product_influencers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='size_and_fit_description',
        ),
        migrations.AddField(
            model_name='category',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='asin_id',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='ASIN'),
        ),
        migrations.AddField(
            model_name='product',
            name='gcid_id',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='GCID'),
        ),
        migrations.AddField(
            model_name='product',
            name='gtnn_id',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='GTNN'),
        ),
        migrations.AddField(
            model_name='product',
            name='on_sale',
            field=models.BooleanField(default=True, verbose_name='Product on sale'),
        ),
        migrations.AddField(
            model_name='product',
            name='requires_shipping',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='Y', max_length=1, verbose_name='Requires shipping.?'),
        ),
        migrations.AddField(
            model_name='product',
            name='ups_id',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='UPS'),
        ),
        migrations.AlterField(
            model_name='product',
            name='rental_status',
            field=models.CharField(choices=[('NON', 'None'), ('REN', 'Rented'), ('RET', 'Returned')], default='NON', max_length=3, verbose_name='Rental Status'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('U', 'Unreserved'), ('R', 'Served'), ('D', 'Draft'), ('L', 'Live')], default='U', max_length=1, verbose_name='Status'),
        ),
    ]
