# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-12 12:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0039_product_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partner.Partner', verbose_name='Brand Information'),
        ),
    ]
