# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-13 06:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0039_auto_20170113_0553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('U', 'Unreserved'), ('R', 'Reserved'), ('D', 'Draft'), ('L', 'Live')], default='U', max_length=1, verbose_name='Status'),
        ),
    ]
