# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-13 07:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0040_auto_20170113_0606'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='wieght',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
