# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-13 12:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0043_auto_20170113_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='partner.Partner', verbose_name='Brand'),
        ),
    ]
