# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-16 05:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0040_auto_20170112_1245'),
        ('catalogue', '0044_auto_20170113_1244'),
    ]

    operations = [
    ]
