# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-23 10:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0010_auto_20170310_1248'),
        ('offer', '0004_conditionaloffer_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='range',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='partner.Partner', verbose_name='Brand'),
        ),
    ]
